#!/bin/bash
#
# 02_binutils
#
# Rob Laswick
# May 2 2013
#
# Script to configure, build, and install binutils.

if [ $# -ne 3 ]; then
echo
echo
echo *** RUNNING SCRIPT STAND ALONE ***
echo
echo
WORKING_DIR=/home/rlaswick/engineering/arm-toolchain-build
PREFIX=/home/rlaswick/opt/arm-toolchain
NUM_CORES=1
else
WORKING_DIR=$1
PREFIX=$2
NUM_CORES=$3
fi

cd ${WORKING_DIR}/build/binutils

rm -rf build
mkdir build
cd build

../configure \
    --target=arm-none-eabi \
    --prefix=${PREFIX} \
    --enable-interwork \
    --enable-multilib \
    --disable-nls \
    --disable-libssp \
    --with-gcc \
    --with-gnu-as \
    --with-gnu-ld \
    --with-system-zlib \
    --with-sysroot=${PREFIX} || exit 1

make -j${NUM_CORES} || exit 1
make install || exit 1

echo
echo
echo
echo binutils built and installed successfully!
echo
