#!/bin/bash
#
# 04_newlib
#
# Rob Laswick
# May 2 2013
#
# Script to configure, build, and install newlib.

if [ $# -ne 3 ]; then
echo
echo
echo *** RUNNING SCRIPT STAND ALONE ***
echo
echo
WORKING_DIR=/home/rlaswick/engineering/arm-toolchain-build
PREFIX=/home/rlaswick/opt/arm-toolchain
NUM_CORES=1
else
WORKING_DIR=$1
PREFIX=$2
NUM_CORES=$3
fi

PATH=${PREFIX}/bin:$PATH

cd ${PREFIX}/bin
ln -fs arm-none-eabi-gcc arm-none-eabi-cc

cd ${WORKING_DIR}/build/newlib

rm -rf build
mkdir build
cd build

../configure \
    --target=arm-none-eabi \
    --prefix=${PREFIX} \
    --enable-interwork \
    --enable-multilib \
    --disable-nls \
    --disable-libssp \
    --with-gcc \
    --with-gnu-as \
    --with-gnu-ld \
    --with-system-zlib \
    --disable-shared \
    --disable-threads \
    --disable-newlib-suplied-syscalls \
    --enable-target-optspace \
    --enable-lto \
    --enable-newlib-reent-small \
    --enable-newlib-multithread \
    CFLAGS="-Os -D__DYNAMIC_REENT__ -DPREFER_SIZE_OVER_SPEED -D__BUFSIZ__=256" \
    --disable-libitm || exit 1

make -j${NUM_CORES} || exit 1
make install || exit 1

echo
echo
echo
echo newlib built and installed successfully!
echo
